/*
 * QitoOS - font registry
 *
 * The system ships several bitmap typefaces, generated at build time by
 * tools/genfont.py. Code draws through a selected font rather than a fixed
 * glyph array, so the interface and terminal faces can differ and either can
 * be changed at runtime from Settings.
 */
#ifndef QITO_FONT_H
#define QITO_FONT_H

#include <kernel/types.h>

typedef enum {
    FONT_REGULAR = 0,
    FONT_BOLD,
} font_weight_t;

struct font {
    const char   *name;          /* human readable, e.g. "Qito Mono"      */
    const char   *id;            /* stable identifier, e.g. "qito-mono"   */
    const char   *description;
    uint8_t       width;
    uint8_t       height;
    uint8_t       baseline;      /* rows from the top to the baseline     */
    uint8_t       first;         /* first character code in the table     */
    uint16_t      count;         /* how many glyphs follow                */
    font_weight_t weight;
    bool_t        monospace;
    const uint8_t *glyphs;       /* count * height bytes, one bit/pixel   */
};

/* Generated by tools/genfont.py. */
extern const struct font qito_fonts[];
extern const int         qito_font_count;

void font_init(void);

/* Look a face up by its identifier, or NULL when it is not present. */
const struct font *font_find(const char *id);
const struct font *font_at(int index);
int                font_count(void);

/*
 * The two faces the rest of the system draws with. The UI font is used for
 * window chrome, panels and applications; the terminal font for the terminal
 * and console, where a monospaced face with unambiguous glyphs matters.
 */
const struct font *font_ui(void);
const struct font *font_terminal(void);

void font_set_ui(const char *id);
void font_set_terminal(const char *id);

/* Row of pixels for one character, or NULL if the font lacks that glyph. */
const uint8_t *font_glyph(const struct font *font, uint32_t character);

/* Pixel width of a string in a given face, accounting for scaling. */
int font_text_width(const struct font *font, const char *text, int scale);

#endif /* QITO_FONT_H */
