#!/usr/bin/env python3
"""
mkqac.py - build Qira Application iCon (.qac) files.

Icons are authored as ASCII art with a colour key, which keeps them
reviewable in source control, and are emitted at several sizes in a single
file. Three encodings are tried per frame and the smallest is kept, so a .qac
is never larger than the raw pixels it represents.

See src/kernel/include/kernel/qac.h for the on-disk layout.

Usage:
    mkqac.py --builtin --output-dir rootfs/usr/share/icons
    mkqac.py --art terminal.txt --name terminal --output terminal.qac
"""

from __future__ import annotations

import argparse
import os
import struct
import sys

MAGIC = b"QACI"
VERSION = 1
HEADER_FMT = "<4sHHII I12s"
HEADER_FMT = "<4sHHIII12s"
HEADER_SIZE = struct.calcsize(HEADER_FMT)
ENTRY_FMT = "<HHBBHII"
ENTRY_SIZE = struct.calcsize(ENTRY_FMT)

QAC_RAW, QAC_RLE, QAC_INDEX = 0, 1, 2

assert HEADER_SIZE == 32, HEADER_SIZE
assert ENTRY_SIZE == 16, ENTRY_SIZE


# --- encoding --------------------------------------------------------------


def encode_raw(pixels: list[int]) -> bytes:
    out = bytearray()
    for pixel in pixels:
        out += bytes(
            [pixel & 0xFF, (pixel >> 8) & 0xFF, (pixel >> 16) & 0xFF, pixel >> 24]
        )
    return bytes(out)


def encode_rle(pixels: list[int]) -> bytes:
    out = bytearray()
    index = 0

    while index < len(pixels):
        pixel = pixels[index]
        run = 1
        while (
            index + run < len(pixels)
            and pixels[index + run] == pixel
            and run < 255
        ):
            run += 1
        out += bytes(
            [run, pixel & 0xFF, (pixel >> 8) & 0xFF, (pixel >> 16) & 0xFF, pixel >> 24]
        )
        index += run

    return bytes(out)


def encode_indexed(pixels: list[int]) -> tuple[bytes, int] | None:
    """Palette encoding, or None when the image needs more than 256 colours."""
    palette: list[int] = []
    lookup: dict[int, int] = {}

    for pixel in pixels:
        if pixel not in lookup:
            if len(palette) >= 256:
                return None
            lookup[pixel] = len(palette)
            palette.append(pixel)

    out = bytearray()
    for colour in palette:
        out += bytes(
            [
                colour & 0xFF,
                (colour >> 8) & 0xFF,
                (colour >> 16) & 0xFF,
                colour >> 24,
            ]
        )
    for pixel in pixels:
        out.append(lookup[pixel])

    return bytes(out), len(palette)


def best_encoding(pixels: list[int]) -> tuple[int, bytes, int]:
    """Return (encoding, data, palette_size) for the smallest representation."""
    candidates: list[tuple[int, int, bytes, int]] = []

    raw = encode_raw(pixels)
    candidates.append((len(raw), QAC_RAW, raw, 0))

    rle = encode_rle(pixels)
    candidates.append((len(rle), QAC_RLE, rle, 0))

    indexed = encode_indexed(pixels)
    if indexed is not None:
        data, palette_size = indexed
        # A palette of 256 is stored as 0 in a byte field.
        candidates.append(
            (len(data), QAC_INDEX, data, palette_size % 256)
        )

    candidates.sort(key=lambda item: item[0])
    _size, encoding, data, palette_size = candidates[0]
    return encoding, data, palette_size


# --- scaling ---------------------------------------------------------------


def scale(pixels: list[int], src: int, dst: int) -> list[int]:
    """Box-filter an icon down, or nearest-neighbour it up."""
    if src == dst:
        return list(pixels)

    out = []
    if dst < src:
        factor = src / dst
        for y in range(dst):
            for x in range(dst):
                x0, x1 = int(x * factor), max(int((x + 1) * factor), int(x * factor) + 1)
                y0, y1 = int(y * factor), max(int((y + 1) * factor), int(y * factor) + 1)

                a = r = g = b = count = 0
                for sy in range(y0, min(y1, src)):
                    for sx in range(x0, min(x1, src)):
                        pixel = pixels[sy * src + sx]
                        pa = pixel >> 24
                        # Weight colour by alpha so transparent pixels do not
                        # drag the edges toward black.
                        a += pa
                        r += ((pixel >> 16) & 0xFF) * pa
                        g += ((pixel >> 8) & 0xFF) * pa
                        b += (pixel & 0xFF) * pa
                        count += 1

                if count == 0 or a == 0:
                    out.append(0)
                else:
                    out.append(
                        ((a // count) << 24)
                        | ((r // a) << 16)
                        | ((g // a) << 8)
                        | (b // a)
                    )
    else:
        for y in range(dst):
            for x in range(dst):
                out.append(pixels[(y * src // dst) * src + (x * src // dst)])

    return out


# --- file assembly ---------------------------------------------------------


def build(frames: dict[int, list[int]], name: str) -> bytes:
    sizes = sorted(frames.keys(), reverse=True)

    entries = bytearray()
    payload = bytearray()

    for size in sizes:
        encoding, data, palette_size = best_encoding(frames[size])
        entries += struct.pack(
            ENTRY_FMT, size, size, encoding, palette_size, 0, len(payload), len(data)
        )
        payload += data

    checksum = sum(payload) & 0xFFFFFFFF

    header = struct.pack(
        HEADER_FMT,
        MAGIC,
        VERSION,
        len(sizes),
        len(payload),
        checksum,
        0,
        name.encode("ascii", "ignore")[:12],
    )

    return bytes(header + entries + payload)


# --- icon artwork ----------------------------------------------------------
#
# Each icon is 32x32, drawn as ASCII art with a per-icon colour key. '.' is
# transparent. Colours are 0xAARRGGBB.

PALETTE = {
    ".": 0x00000000,
    "K": 0xFF1A1D28,  # near-black outline
    "W": 0xFFF2F5FA,  # white
    "G": 0xFF8A93A8,  # grey
    "D": 0xFF3A4152,  # dark grey
    "B": 0xFF5AA0F0,  # blue
    "b": 0xFF2E6FC0,  # dark blue
    "C": 0xFF56D6D6,  # cyan
    "c": 0xFF2E9EA8,  # dark cyan
    "N": 0xFF78D278,  # green
    "n": 0xFF3E9B4F,  # dark green
    "Y": 0xFFF0C24A,  # amber
    "y": 0xFFC08820,  # dark amber
    "R": 0xFFE8635F,  # red
    "P": 0xFFB07BE8,  # purple
    "p": 0xFF7A4FB0,  # dark purple
    "O": 0xFFF08A3C,  # orange
}

ICONS: dict[str, list[str]] = {}


def icon(name: str, art: str) -> None:
    rows = [row for row in art.strip("\n").split("\n") if row]
    assert len(rows) == 32, f"{name}: {len(rows)} rows, expected 32"
    for index, row in enumerate(rows):
        assert len(row) == 32, f"{name} row {index}: {len(row)} wide, expected 32"
    ICONS[name] = rows


icon(
    "terminal",
    """
................................
................................
..KKKKKKKKKKKKKKKKKKKKKKKKKKKK..
..KDDDDDDDDDDDDDDDDDDDDDDDDDDK..
..KDGGGGGGGGGGGGGGGGGGGGGGGGDK..
..KDKKKKKKKKKKKKKKKKKKKKKKKKDK..
..KDKKKKKKKKKKKKKKKKKKKKKKKKDK..
..KDKKNNKKKKKKKKKKKKKKKKKKKKDK..
..KDKKKNNKKKKKKKKKKKKKKKKKKKDK..
..KDKKKKNNKKKKKKKKKKKKKKKKKKDK..
..KDKKKKKNNKKKKKKKKKKKKKKKKKDK..
..KDKKKKNNKKKKKKKKKKKKKKKKKKDK..
..KDKKKNNKKKKKKKKKKKKKKKKKKKDK..
..KDKKNNKKKKKKKKKKKKKKKKKKKKDK..
..KDKKKKKKKKKKKKKKKKKKKKKKKKDK..
..KDKKKNNNNNNNNNNKKKKKKKKKKKDK..
..KDKKKKKKKKKKKKKKKKKKKKKKKKDK..
..KDKKKKKKKKKKKKKKKKKKKKKKKKDK..
..KDKKWWWWWWKKKKKKKKKKKKKKKKDK..
..KDKKKKKKKKKKKKKKKKKKKKKKKKDK..
..KDKKKKKKKKKKKKKKKKKKKKKKKKDK..
..KDKKKKKKKKKKKKKKKKKKKKKKKKDK..
..KDKKKKKKKKKKKKKKKKKKKKKKKKDK..
..KDKKKKKKKKKKKKKKKKKKKKKKKKDK..
..KDKKKKKKKKKKKKKKKKKKKKKKKKDK..
..KDDDDDDDDDDDDDDDDDDDDDDDDDDK..
..KKKKKKKKKKKKKKKKKKKKKKKKKKKK..
................................
................................
................................
................................
................................
""",
)

icon(
    "files",
    """
................................
................................
................................
.....YYYYYYY....................
....YyyyyyyyY...................
...YyYYYYYYYyYYYYYYYYYYYYYYYY...
...YyYYYYYYYYYYYYYYYYYYYYYYYyY..
...YyYYYYYYYYYYYYYYYYYYYYYYYyY..
...YyYYYYYYYYYYYYYYYYYYYYYYYyY..
...YyYYYYYYYYYYYYYYYYYYYYYYYyY..
...YyYYYYYYYYYYYYYYYYYYYYYYYyY..
...YyYYWWWWWWWWWWWWWWWWWWYYYyY..
...YyYYYYYYYYYYYYYYYYYYYYYYYyY..
...YyYYWWWWWWWWWWWWWWWWWWYYYyY..
...YyYYYYYYYYYYYYYYYYYYYYYYYyY..
...YyYYWWWWWWWWWWWWWWWWWWYYYyY..
...YyYYYYYYYYYYYYYYYYYYYYYYYyY..
...YyYYWWWWWWWWWWWWWWWWWWYYYyY..
...YyYYYYYYYYYYYYYYYYYYYYYYYyY..
...YyYYWWWWWWWWWWWWWWWWWWYYYyY..
...YyYYYYYYYYYYYYYYYYYYYYYYYyY..
...YyYYYYYYYYYYYYYYYYYYYYYYYyY..
...YyYYYYYYYYYYYYYYYYYYYYYYYyY..
...YyYYYYYYYYYYYYYYYYYYYYYYYyY..
...YyyyyyyyyyyyyyyyyyyyyyyyyyY..
....YYYYYYYYYYYYYYYYYYYYYYYYY...
................................
................................
................................
................................
................................
................................
""",
)

icon(
    "editor",
    """
................................
................................
....WWWWWWWWWWWWWWWWWWWWWW......
....WGGGGGGGGGGGGGGGGGGGGW......
....WGWWWWWWWWWWWWWWWWWWGW......
....WGWKKKKKKKKKKKKKKWWWGW......
....WGWWWWWWWWWWWWWWWWWWGW......
....WGWKKKKKKKKKKKKKKKKWGW......
....WGWWWWWWWWWWWWWWWWWWGW......
....WGWKKKKKKKKKKKWWWWWWGW......
....WGWWWWWWWWWWWWWWWWWWGW......
....WGWKKKKKKKKKKKKKKKKWGW......
....WGWWWWWWWWWWWWWWWWWWGW......
....WGWKKKKKKKKKWWWWWWWWGW......
....WGWWWWWWWWWWWWWWWWWWGW......
....WGWKKKKKKKKKKKKKKKKWGW......
....WGWWWWWWWWWWWWWWWWWWGW......
....WGWKKKKKKKKKKKKWWWWWGW......
....WGWWWWWWWWWWWWWWWWWWGW.OO...
....WGWKKKKKKKKKKKKKKKKWGW.OyO..
....WGWWWWWWWWWWWWWWWWWWGWOyyO..
....WGWKKKKKKKKKWWWWWWWWGOyyO...
....WGWWWWWWWWWWWWWWWWWWOyyOW...
....WGWKKKKKKKKKKKKKKKKOyyOGW...
....WGWWWWWWWWWWWWWWWWOyyOWGW...
....WGGGGGGGGGGGGGGGGOyyOGGGW...
....WWWWWWWWWWWWWWWWOyyOWWWWW...
...................OyyO.........
..................OyyO..........
..................OOO...........
................................
................................
""",
)

icon(
    "settings",
    """
................................
................................
..............PP................
.............PppP...............
............PppppP..............
...PPP......PppppP......PPP.....
..PpppP.....PppppP.....PpppP....
..PppppP....PppppP....PppppP....
...PppppP...PppppP...PppppP.....
....PppppPPPPppppPPPPppppP......
.....PppppppppppppppppppP.......
......PpppppppppppppppP.........
.......PpppppKKKKppppP..........
.PPPPPPPppppKKKKKKppppPPPPPPP...
.PppppppppppKKKKKKppppppppppP...
.PppppppppppKKKKKKppppppppppP...
.PppppppppppKKKKKKppppppppppP...
.PPPPPPPppppKKKKKKppppPPPPPPP...
.......PpppppKKKKppppP..........
......PpppppppppppppppP.........
.....PppppppppppppppppppP.......
....PppppPPPPppppPPPPppppP......
...PppppP...PppppP...PppppP.....
..PppppP....PppppP....PppppP....
..PpppP.....PppppP.....PpppP....
...PPP......PppppP......PPP.....
............PppppP..............
.............PppP...............
..............PP................
................................
................................
................................
""",
)

icon(
    "browser",
    """
................................
................................
..........BBBBBBBBBB............
.......BBBbbbbbbbbbbBBB.........
.....BBbbbbbbbbbbbbbbbbBB.......
....BbbbbbWWbbbbbbWWbbbbbB......
...BbbbbWWbbbbbbbbbbWWbbbbB.....
..BbbbbWbbbbbbbbbbbbbbWbbbbB....
..BbbbWbbbbWWWWWWWWbbbbWbbbB....
.BbbbWbbbWWbbbbbbbbWWbbbWbbbB...
.BbbbWbbWbbbbbbbbbbbbWbbWbbbB...
.BbbWbbbWbbbbbbbbbbbbWbbbWbbB...
BbbbWbbWbbbbbbbbbbbbbbWbbWbbbB..
BWWWWWWWWWWWWWWWWWWWWWWWWWWWWB..
BbbbWbbWbbbbbbbbbbbbbbWbbWbbbB..
.BbbWbbbWbbbbbbbbbbbbWbbbWbbB...
.BbbbWbbWbbbbbbbbbbbbWbbWbbbB...
.BbbbWbbbWWbbbbbbbbWWbbbWbbbB...
..BbbbWbbbbWWWWWWWWbbbbWbbbB....
..BbbbbWbbbbbbbbbbbbbbWbbbbB....
...BbbbbWWbbbbbbbbbbWWbbbbB.....
....BbbbbbWWbbbbbbWWbbbbbB......
.....BBbbbbbbbbbbbbbbbbBB.......
.......BBBbbbbbbbbbbBBB.........
..........BBBBBBBBBB............
................................
................................
................................
................................
................................
................................
................................
""",
)

icon(
    "monitor",
    """
................................
................................
..RRRRRRRRRRRRRRRRRRRRRRRRRRRR..
..RKKKKKKKKKKKKKKKKKKKKKKKKKKR..
..RKKKKKKKKKKKKKKKKKKKKKKKKKKR..
..RKKKKKKKKKKKKKKKKKKKKKKKKKKR..
..RKKKKKKKKKKKKKKKKKKKKKKKKKKR..
..RKKKKKKKKKKKKKKKKKKKNKKKKKKR..
..RKKKKKKKKKKKKKKKKKKNNNKKKKKR..
..RKKKKKKKKKNKKKKKKKKNNNKKKKKR..
..RKKKKKKKKNNNKKKKKKNNNNNKKKKR..
..RKKKNKKKKNNNKKKKKKNNNNNKKKKR..
..RKKNNNKKNNNNNKKKKNNNNNNNKKKR..
..RKKNNNKKNNNNNKKKKNNNNNNNKNKR..
..RKNNNNNNNNNNNKKKNNNNNNNNNNNR..
..RKNNNNNNNNNNNNKKNNNNNNNNNNNR..
..RNNNNNNNNNNNNNNNNNNNNNNNNNNR..
..RKKKKKKKKKKKKKKKKKKKKKKKKKKR..
..RRRRRRRRRRRRRRRRRRRRRRRRRRRR..
....RRRRRRRRRRRRRRRRRRRRRRRR....
.......RRRRRRRRRRRRRRRRRR.......
..........RRRRRRRRRRRR..........
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
""",
)

icon(
    "calculator",
    """
................................
................................
....OOOOOOOOOOOOOOOOOOOOOO......
....OyyyyyyyyyyyyyyyyyyyyO......
....OyKKKKKKKKKKKKKKKKKKyO......
....OyKWWWWWWWWWWWWWWWWKyO......
....OyKKKKKKKKKKKKKKKKKKyO......
....OyyyyyyyyyyyyyyyyyyyyO......
....OyWWWWyWWWWyWWWWyWWWWO......
....OyWWWWyWWWWyWWWWyWWWWO......
....OyWWWWyWWWWyWWWWyWWWWO......
....OyyyyyyyyyyyyyyyyyyyyO......
....OyWWWWyWWWWyWWWWyWWWWO......
....OyWWWWyWWWWyWWWWyWWWWO......
....OyWWWWyWWWWyWWWWyWWWWO......
....OyyyyyyyyyyyyyyyyyyyyO......
....OyWWWWyWWWWyWWWWyBBBBO......
....OyWWWWyWWWWyWWWWyBBBBO......
....OyWWWWyWWWWyWWWWyBBBBO......
....OyyyyyyyyyyyyyyyyBBBBO......
....OyWWWWWWWWWyWWWWyBBBBO......
....OyWWWWWWWWWyWWWWyBBBBO......
....OyWWWWWWWWWyWWWWyBBBBO......
....OyyyyyyyyyyyyyyyyyyyyO......
....OOOOOOOOOOOOOOOOOOOOOO......
................................
................................
................................
................................
................................
................................
................................
""",
)

icon(
    "package",
    """
................................
................................
..............KK................
............KKyyKK..............
..........KKyyyyyyKK............
........KKyyyyyyyyyyKK..........
......KKyyyyyyyyyyyyyyKK........
....KKyyyyyyyyyyyyyyyyyyKK......
..KKyyyyyyyyyyyyyyyyyyyyyyKK....
.KYyyyyyyyyyyyyyyyyyyyyyyyyYK...
.KYYyyyyyyyyyyyyyyyyyyyyyyYYK...
.KYyYYyyyyyyyyyyyyyyyyyyYYyYK...
.KYyyyYYyyyyyyyyyyyyyyYYyyyYK...
.KYyyyyyYYyyyyyyyyyyYYyyyyyYK...
.KYyyyyyyyYYyyyyyyYYyyyyyyyYK...
.KYyyyyyyyyyYYyyYYyyyyyyyyyYK...
.KYyyyyyyyyyyyYYyyyyyyyyyyyYK...
.KYyyyyyyyyyyyyyyyyyyyyyyyyYK...
.KYyyyyyyyyyyyyyyyyyyyyyyyyYK...
.KYyyyyyyyyyyyyyyyyyyyyyyyyYK...
.KYyyyyyyyyyyyyyyyyyyyyyyyyYK...
.KYyyyyyyyyyyyyyyyyyyyyyyyyYK...
.KYyyyyyyyyyyyyyyyyyyyyyyyyYK...
.KYyyyyyyyyyyyyyyyyyyyyyyyyYK...
.KYYYYYYYYYYYYYYYYYYYYYYYYYYK...
..KKKKKKKKKKKKKKKKKKKKKKKKKK....
................................
................................
................................
................................
................................
................................
""",
)

icon(
    "network",
    """
................................
................................
..........CCCCCCCCCC............
.......CCCcccccccccCCC..........
.....CCcccccccccccccccCC........
....CccccccccccccccccccCC.......
...CccccccccccccccccccccC.......
..CccccccccccccccccccccccC......
..CccccccccccccccccccccccC......
.CcccccccccccccccccccccccC......
.CcccccccccccccccccccccccC......
.CcccccccccccccccccccccccC......
..CccccccccccccccccccccccC......
..CccccccccccccccccccccccC......
...CccccccccccccccccccccC.......
....CccccccccccccccccccC........
.....CCcccccccccccccccC.........
.......CCCcccccccccCCC..........
..........CCCCCCCCCC............
..............CC................
..............CC................
.........CCCCCCCCCCCC...........
........CccccccccccccC..........
........CcWWcWWcWWcccC..........
........CccccccccccccC..........
........CCCCCCCCCCCCCC..........
................................
................................
................................
................................
................................
................................
""",
)

icon(
    "clock",
    """
................................
................................
..........KKKKKKKKKK............
.......KKKWWWWWWWWWWKKK.........
.....KKWWWWWWWWWWWWWWWWKK.......
....KWWWWWWWWKKWWWWWWWWWWK......
...KWWWWWWWWWKKWWWWWWWWWWWK.....
..KWWWWWWWWWWKKWWWWWWWWWWWWK....
..KWWWWWWWWWWKKWWWWWWWWWWWWK....
.KWWWWWWWWWWWKKWWWWWWWWWWWWWK...
.KWWWWWWWWWWWKKWWWWWWWWWWWWWK...
.KWWKKWWWWWWWKKWWWWWWWWKKWWWK...
.KWWKKWWWWWWWKKWWWWWWWWKKWWWK...
.KWWWWWWWWWWWKKWWWWWWWWWWWWWK...
.KWWWWWWWWWWWKBBBBBBBWWWWWWWK...
.KWWWWWWWWWWWWBBBBBBBWWWWWWWK...
.KWWWWWWWWWWWWWWWWWWWWWWWWWWK...
.KWWWWWWWWWWWWWWWWWWWWWWWWWWK...
.KWWWWWWWWWWWWWWWWWWWWWWWWWWK...
.KWWWWWWWWWWWWWWWWWWWWWWWWWWK...
..KWWWWWWWWWWWWWWWWWWWWWWWWK....
..KWWWWWWWWWWWWWWWWWWWWWWWWK....
...KWWWWWWWWWWWWWWWWWWWWWWK.....
....KWWWWWWWWWWWWWWWWWWWWK......
.....KKWWWWWWWWWWWWWWWWKK.......
.......KKKWWWWWWWWWWKKK.........
..........KKKKKKKKKK............
................................
................................
................................
................................
................................
""",
)

icon(
    "help",
    """
................................
................................
..........NNNNNNNNNN............
.......NNNnnnnnnnnnnNNN.........
.....NNnnnnnnnnnnnnnnnnNN.......
....NnnnnnnnnnnnnnnnnnnnnN......
...NnnnnnnnWWWWWWWnnnnnnnnN.....
..NnnnnnnWWWWWWWWWWWnnnnnnnN....
..NnnnnnWWWnnnnnnnWWWnnnnnnN....
.NnnnnnWWWnnnnnnnnnWWWnnnnnnN...
.NnnnnnWWWnnnnnnnnnWWWnnnnnnN...
.NnnnnnnnnnnnnnnnnWWWnnnnnnnN...
.NnnnnnnnnnnnnnnWWWWnnnnnnnnN...
.NnnnnnnnnnnnnWWWWnnnnnnnnnnN...
.NnnnnnnnnnnWWWWnnnnnnnnnnnnN...
.NnnnnnnnnnWWWnnnnnnnnnnnnnnN...
.NnnnnnnnnnWWWnnnnnnnnnnnnnnN...
.NnnnnnnnnnnnnnnnnnnnnnnnnnnN...
.NnnnnnnnnnWWWnnnnnnnnnnnnnnN...
.NnnnnnnnnWWWWWnnnnnnnnnnnnnN...
..NnnnnnnnWWWWWnnnnnnnnnnnnN....
..NnnnnnnnnWWWnnnnnnnnnnnnnN....
...NnnnnnnnnnnnnnnnnnnnnnnN.....
....NnnnnnnnnnnnnnnnnnnnnN......
.....NNnnnnnnnnnnnnnnnnNN.......
.......NNNnnnnnnnnnnNNN.........
..........NNNNNNNNNN............
................................
................................
................................
................................
................................
""",
)

icon(
    "qira",
    """
................................
................................
..........BBBBBBBBBB............
.......BBBBbbbbbbbbBBBB.........
.....BBbbbbbbbbbbbbbbbbBB.......
....BbbbbbbbbbbbbbbbbbbbbB......
...BbbbbbCCCCCCCCCCCCbbbbbB.....
..BbbbbCCCCCCCCCCCCCCCCbbbbB....
..BbbbCCCCbbbbbbbbbbCCCCbbbB....
.BbbbCCCCbbbbbbbbbbbbCCCCbbbB...
.BbbbCCCbbbbbbbbbbbbbbCCCbbbB...
.BbbCCCCbbbbbbbbbbbbbbCCCCbbB...
.BbbCCCbbbbbbbbbbbbbbbbCCCbbB...
.BbbCCCbbbbbbbbbbbbbbbbCCCbbB...
.BbbCCCbbbbbbbbbbbbbbbbCCCbbB...
.BbbCCCbbbbbbbbbbbbbbbbCCCbbB...
.BbbCCCbbbbbbbbbbbbbbbbCCCbbB...
.BbbCCCCbbbbbbbbbbbbCCCCCCbbB...
.BbbbCCCbbbbbbbbbbbCCCCCbbbbB...
.BbbbCCCCbbbbbbbbCCCCCCbbbbB....
..BbbbCCCCbbbbbCCCCCCCCbbbB.....
..BbbbbCCCCCCCCCCCbbCCCCbbB.....
...BbbbbbCCCCCCCbbbbbCCCCbB.....
....BbbbbbbbbbbbbbbbbbCCCCB.....
.....BBbbbbbbbbbbbbbbbbCCCC.....
.......BBBbbbbbbbbbbBBBBCCC.....
..........BBBBBBBBBB.....CC.....
................................
................................
................................
................................
................................
""",
)


def art_to_pixels(rows: list[str], palette: dict[str, int]) -> list[int]:
    pixels = []
    for row in rows:
        for char in row:
            if char not in palette:
                raise SystemExit(f"error: unknown colour key {char!r}")
            pixels.append(palette[char])
    return pixels


def load_art_file(path: str) -> list[str]:
    with open(path) as handle:
        rows = [line.rstrip("\n") for line in handle if line.strip()]
    if len(rows) != 32:
        raise SystemExit(f"error: {path} has {len(rows)} rows, expected 32")
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description="Build .qac icon files")
    parser.add_argument("--builtin", action="store_true",
                        help="emit every built-in icon")
    parser.add_argument("--output-dir", default=None)
    parser.add_argument("--art", default=None, help="a 32x32 ASCII art file")
    parser.add_argument("--name", default="icon")
    parser.add_argument("--output", default=None)
    parser.add_argument("--sizes", default="32,24,16",
                        help="comma separated frame sizes")
    args = parser.parse_args()

    sizes = [int(value) for value in args.sizes.split(",")]

    if args.builtin:
        if not args.output_dir:
            raise SystemExit("error: --builtin needs --output-dir")
        os.makedirs(args.output_dir, exist_ok=True)

        total = 0
        for name, rows in sorted(ICONS.items()):
            pixels = art_to_pixels(rows, PALETTE)
            frames = {size: scale(pixels, 32, size) for size in sizes}
            data = build(frames, name)

            path = os.path.join(args.output_dir, f"{name}.qac")
            with open(path, "wb") as handle:
                handle.write(data)

            raw_size = 32 * 32 * 4
            print(f"  {name:12s} {len(data):6d} bytes  "
                  f"({len(sizes)} frames, {raw_size // max(len(data), 1)}x smaller "
                  f"than one raw 32x32 frame)")
            total += len(data)

        print(f"{len(ICONS)} icons, {total} bytes total")
        return 0

    if args.art:
        rows = load_art_file(args.art)
        pixels = art_to_pixels(rows, PALETTE)
        frames = {size: scale(pixels, 32, size) for size in sizes}
        data = build(frames, args.name)

        output = args.output or f"{args.name}.qac"
        with open(output, "wb") as handle:
            handle.write(data)
        print(f"wrote {output} ({len(data)} bytes)")
        return 0

    parser.print_help()
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
