#!/usr/bin/env python3
"""
runbochs.py - boot a QitoOS ISO under the Bochs x86 emulator.

Bochs is used by the automated boot tests because it is easy to build from
source in restricted environments and it faithfully emulates the BIOS
interfaces (INT 13h extensions, VBE) that the Qito bootloader relies on.

The generated configuration wires the serial port to a file so the test
harness can assert on the kernel's boot log.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile

DEFAULT_PREFIXES = ["/opt/bochs", "/usr/local", "/usr"]


def find_bochs() -> tuple[str, str]:
    """Return (bochs binary, share directory containing the BIOS images)."""
    binary = shutil.which("bochs")
    if binary is None:
        for prefix in DEFAULT_PREFIXES:
            candidate = os.path.join(prefix, "bin", "bochs")
            if os.path.isfile(candidate):
                binary = candidate
                break
    if binary is None:
        raise SystemExit("error: bochs not found; install it or set PATH")

    prefix = os.path.dirname(os.path.dirname(os.path.abspath(binary)))
    share = os.path.join(prefix, "share", "bochs")
    if not os.path.isdir(share):
        for candidate in DEFAULT_PREFIXES:
            alt = os.path.join(candidate, "share", "bochs")
            if os.path.isdir(alt):
                share = alt
                break
    return binary, share


def write_config(
    path: str,
    iso: str,
    share: str,
    serial_log: str,
    memory: int,
    display: str,
) -> None:
    bios = os.path.join(share, "BIOS-bochs-latest")
    vgabios = os.path.join(share, "VGABIOS-lgpl-latest.bin")

    config = f"""# Generated by tools/runbochs.py - do not edit.
romimage: file="{bios}"
vgaromimage: file="{vgabios}"
megs: {memory}

# Boot from the QitoOS CD.
ata0: enabled=1, ioaddr1=0x1f0, ioaddr2=0x3f0, irq=14
ata0-master: type=cdrom, path="{iso}", status=inserted
boot: cdrom

# The kernel log is mirrored to COM1.
com1: enabled=1, mode=file, dev="{serial_log}"

# Devices QitoOS drivers probe for.
mouse: enabled=1, type=ps2
clock: sync=none, time0=local
# A modern 64-bit CPU model so long mode, SSE2 and the CPUID leaves the
# kernel queries are all available.
cpu: model=corei7_haswell_4770, count=1, ips=80000000, reset_on_triple_fault=1
pci: enabled=1, chipset=i440fx

# No host audio device is available in CI containers.
sound: driver=dummy, waveoutdrv=dummy, waveindrv=dummy

display_library: {display}
vga: extension=vbe, update_freq=10

log: -
panic: action=report
error: action=report
info: action=ignore
debug: action=ignore
"""
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(config)


def main() -> int:
    parser = argparse.ArgumentParser(description="Run QitoOS under Bochs")
    parser.add_argument("--iso", required=True)
    parser.add_argument("--memory", type=int, default=512)
    parser.add_argument(
        "--timeout", type=int, default=60, help="seconds before Bochs is killed"
    )
    parser.add_argument("--serial-log", default=None)
    parser.add_argument(
        "--interactive",
        action="store_true",
        help="use a graphical display instead of the headless stub",
    )
    parser.add_argument("--keep-config", action="store_true")
    args = parser.parse_args()

    iso = os.path.abspath(args.iso)
    if not os.path.isfile(iso):
        raise SystemExit(f"error: {iso} does not exist")

    binary, share = find_bochs()

    workdir = tempfile.mkdtemp(prefix="qito-bochs-")
    config_path = os.path.join(workdir, "bochsrc")
    serial_log = os.path.abspath(args.serial_log or os.path.join(workdir, "serial.log"))

    # `nogui` runs headless, which is what CI needs.
    display = "x" if args.interactive else "nogui"
    write_config(config_path, iso, share, serial_log, args.memory, display)

    command = [binary, "-q", "-f", config_path, "-log", os.path.join(workdir, "bochs.log")]

    print(f"running: {' '.join(command)}", file=sys.stderr)
    try:
        result = subprocess.run(
            command,
            timeout=args.timeout,
            capture_output=True,
            text=True,
            cwd=workdir,
        )
        stdout, stderr, code = result.stdout, result.stderr, result.returncode
    except subprocess.TimeoutExpired as expired:
        # A timeout is the normal outcome: the OS keeps running until killed.
        stdout = expired.stdout.decode() if expired.stdout else ""
        stderr = expired.stderr.decode() if expired.stderr else ""
        code = 0

    if os.path.isfile(serial_log):
        with open(serial_log, "r", errors="replace") as handle:
            sys.stdout.write(handle.read())
    else:
        print("(no serial output captured)", file=sys.stderr)

    if stderr.strip():
        print("--- bochs stderr ---", file=sys.stderr)
        print(stderr[-4000:], file=sys.stderr)
    if stdout.strip():
        print("--- bochs stdout ---", file=sys.stderr)
        print(stdout[-4000:], file=sys.stderr)

    if not args.keep_config:
        shutil.rmtree(workdir, ignore_errors=True)
    return code


if __name__ == "__main__":
    raise SystemExit(main())
